name: xeus-kernels
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core >=0.3.0,<0.4.0
  - pip:
    - jupyterlite-xeus>=0.2.0a0,<0.3